{{- if eq .Values.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "plugin-nvme-temp.fullname" . }}
  labels:
    {{- include "plugin-nvme-temp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "plugin-nvme-temp.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "plugin-nvme-temp.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plugin-nvme-temp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
        {{ if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
        {{- end }}
        {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
        {{- end }}
        {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
        {{- end }}
        {{- if .Values.args }}
          args:
          {{- toYaml .Values.args | nindent 6 }}
        {{- end}}  
      volumes:
        {{- toYaml .Values.Volumes | nindent 8 }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
